# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_seq <- function(n, K) {
    .Call(`_ClusterNormal_init_seq`, n, K)
}

log_sum_exp <- function(log_unnorm_prob) {
    .Call(`_ClusterNormal_log_sum_exp`, log_unnorm_prob)
}

fmm_log_alloc_prob <- function(K, i, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0) {
    .Call(`_ClusterNormal_fmm_log_alloc_prob`, K, i, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0)
}

fmm_samp_new <- function(K, log_alloc) {
    .Call(`_ClusterNormal_fmm_samp_new`, K, log_alloc)
}

fmm_mod <- function(t, K, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0) {
    .Call(`_ClusterNormal_fmm_mod`, t, K, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0)
}

log_alloc_prob <- function(i, active_clus, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0) {
    .Call(`_ClusterNormal_log_alloc_prob`, i, active_clus, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0)
}

samp_new <- function(log_prob_mat) {
    .Call(`_ClusterNormal_samp_new`, log_prob_mat)
}

our_allocate <- function(old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, old_alpha) {
    .Call(`_ClusterNormal_our_allocate`, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, old_alpha)
}

rcpparma_hello_world <- function() {
    .Call(`_ClusterNormal_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ClusterNormal_rcpparma_bothproducts`, x)
}

