# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sum_exp <- function(log_unnorm_prob) {
    .Call(`_ClusterNormal_log_sum_exp`, log_unnorm_prob)
}

log_marginal <- function(y, ci, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster) {
    .Call(`_ClusterNormal_log_marginal`, y, ci, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster)
}

log_posterior <- function(y_new, data, ci, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster) {
    .Call(`_ClusterNormal_log_posterior`, y_new, data, ci, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster)
}

rmultinom_1 <- function(unnorm_prob, N) {
    .Call(`_ClusterNormal_rmultinom_1`, unnorm_prob, N)
}

fmm_iter <- function(K, old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster) {
    .Call(`_ClusterNormal_fmm_iter`, K, old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster)
}

fmm <- function(iter, K, old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster) {
    .Call(`_ClusterNormal_fmm`, iter, K, old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster)
}

adjust_alpha <- function(cluster_assign, old_alpha) {
    .Call(`_ClusterNormal_adjust_alpha`, cluster_assign, old_alpha)
}

split_launch <- function(old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, sm_cluster, S_index) {
    .Call(`_ClusterNormal_split_launch`, old_assign, y, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, sm_cluster, S_index)
}

log_proposal <- function(c1, c2, y, xi_cluster, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, sm_cluster, S_index) {
    .Call(`_ClusterNormal_log_proposal`, c1, c2, y, xi_cluster, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, sm_cluster, S_index)
}

SFDM_realloc <- function(old_assign, y, alpha_vec, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster) {
    .Call(`_ClusterNormal_SFDM_realloc`, old_assign, y, alpha_vec, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster)
}

SFDM_SM <- function(K, old_assign, y, alpha_vec, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster, launch_iter, a_theta, b_theta) {
    .Call(`_ClusterNormal_SFDM_SM`, K, old_assign, y, alpha_vec, mu0_cluster, lambda_cluster, a_sigma_cluster, b_sigma_cluster, xi_cluster, launch_iter, a_theta, b_theta)
}

log_alloc_prob <- function(i, active_clus, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, restricted) {
    .Call(`_ClusterNormal_log_alloc_prob`, i, active_clus, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, restricted)
}

samp_new <- function(log_prob_mat) {
    .Call(`_ClusterNormal_samp_new`, log_prob_mat)
}

SFDM_allocate <- function(K, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, old_alpha) {
    .Call(`_ClusterNormal_SFDM_allocate`, K, old_assign, xi, y, a_sigma, b_sigma, lambda, mu0, old_alpha)
}

SFDM_alpha <- function(clus_assign, xi, old_alpha, old_u) {
    .Call(`_ClusterNormal_SFDM_alpha`, clus_assign, xi, old_alpha, old_u)
}

rcpparma_hello_world <- function() {
    .Call(`_ClusterNormal_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ClusterNormal_rcpparma_bothproducts`, x)
}

