# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

active_inactive <- function(K, clus_assign) {
    .Call(`_ClusterNormal_active_inactive`, K, clus_assign)
}

sample_clus <- function(norm_probs, active_clus) {
    .Call(`_ClusterNormal_sample_clus`, norm_probs, active_clus)
}

log_marginal_univariate <- function(y, a_sigma_K, b_sigma_K, lambda_K, mu_0_K) {
    .Call(`_ClusterNormal_log_marginal_univariate`, y, a_sigma_K, b_sigma_K, lambda_K, mu_0_K)
}

log_allocate_prob <- function(i, current_assign, xi, y, gamma_hyper_mat, active_clus) {
    .Call(`_ClusterNormal_log_allocate_prob`, i, current_assign, xi, y, gamma_hyper_mat, active_clus)
}

log_sum_exp <- function(log_unnorm_prob) {
    .Call(`_ClusterNormal_log_sum_exp`, log_unnorm_prob)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call(`_ClusterNormal_rdirichlet_cpp`, num_samples, alpha_m)
}

expand_step_univariate <- function(K, old_assign, alpha, xi, y, mu_0, a_sigma, b_sigma, lambda, a_theta, b_theta) {
    .Call(`_ClusterNormal_expand_step_univariate`, K, old_assign, alpha, xi, y, mu_0, a_sigma, b_sigma, lambda, a_theta, b_theta)
}

cluster_assign <- function(K, old_assign, xi, y, gamma_hyper, alpha) {
    .Call(`_ClusterNormal_cluster_assign`, K, old_assign, xi, y, gamma_hyper, alpha)
}

split_merge <- function(K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, sm_iter) {
    .Call(`_ClusterNormal_split_merge`, K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, sm_iter)
}

update_alpha <- function(K, alpha, xi, old_assign) {
    .Call(`_ClusterNormal_update_alpha`, K, alpha, xi, old_assign)
}

cluster_func <- function(K, K_init, y, xi, gamma_hyper, a_theta, b_theta, sm_iter, all_iter, print_iter, iter_print) {
    .Call(`_ClusterNormal_cluster_func`, K, K_init, y, xi, gamma_hyper, a_theta, b_theta, sm_iter, all_iter, print_iter, iter_print)
}

rcpparma_hello_world <- function() {
    .Call(`_ClusterNormal_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ClusterNormal_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ClusterNormal_rcpparma_bothproducts`, x)
}

